paths:
  media_root: "media"
  db_root: "db"

video:
  framge_interval: 5

detect:
  conf_thresh : 0.9
  min_face_px : 60

align:
  size: [112, 112]

superres:
  enabled: false
  apply_if_small_px: 90
  apply_if_blurry: true

embed:
  model: "facenet_vggface2"
  dim: 512

search:
  top_k: 10
  cosine_thresh: 0.65

index:
  faiss_path: "db/faiss.index"
  vectors_path: "db/vectors.npy"

sqlserver:
  dsn: ""     # prefer DSN OR full connection string, keep one
  conn_str: "mssql+pyodbc://USER:PASS@SERVER:1433/YourDb?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"